feat(ui): implementation of mantainance page on the admin section
fossology/FOSSologyUI pull request #232
Opened 2022-06-20 05:42 UTC by dushimsam

Signed-off-by: dushimsam <dushsam100@gmail.com>

## Description

Implemented the maintenance page from the Admin section. The page is on the route `/admin/mantainance`

### Changes

1. Created a new directory ,`src/pages/admin/Mantainance/index.jsx`
3. Imported and added the new page in the `src/Routes.jsx` as a part of `AdminLayout`

![Image 1](https://lh3.googleusercontent.com/KJZjWm51-GAOXpH6iZHw_KmHNvEEOfUDwqqjDW5iDpsgQQyv6XtGb0ZX_7F6m47T0-LCHtJaTld5M_lO9HgYA-GNOOJEqs1wR3NQB7IEcRPQJKI0k4PkZT7zUyX2j0Ksi-yoQp4XqHJ3ryGrUpJa9PnVIFRaMtCNkQ_jOZa-RRA4a2UBtCbxa-B_T6x0VtDL45WkylwcnIoqEVrgFMgH3iZlfgegv2LP6lXQDsBQ0aT1f_BGWSw6ew-Gt9A406s09SRtm6Vcdfns60pTMgNTX6EBKSP1Eu1pHSbESSzfJQZJaQZGQTdCbvtsovQQAHweq9TvpHjpskXE5co1UryzzzV0_eyZZglsOPtx66F9g-xhff9xIH4Jhz5jO7ngM8whma6uQkPdAApZ_UtdFEi548454lSrb9atSzmyNBd6c1HX-baIE9sonXGOUqcmTJDB6DzTbi2PPO5jrkpTX-3PBQMY0T9RF8fVfeWF5aCAOR9c6IkEdp-fyqWocQMCIJKYxp_BVstkRXGOjPEvfJaboQHYYm698TMjVRwogSZlo6RpDy5b3YZo4fyVHuaG9e45HI_BgeItDDpcZvFSQRC3NGAXlOk2v0rLggUPrW1xLOJXJKVURl1dBzbziyHuxnsjZq40MtupQoe34rRsn3BaEBIe5uoBTWVdABeTk_n-3Li0xq08fJg03WGYOI5XEcOo7QGy9KLheqbqFUWpFi4vLFmcMIe-tpg6Q_5NgkR_B4_G0STJOUEooDwzlXlnRg=w698-h544-no?authuser=0) 

5. Added a new navigation dropdown Item as a part of the admin dropdowns.

![image 2](https://lh3.googleusercontent.com/nXHWgGhsXgoATUTzUdztRVoXpcT8IFQFYmxM0yFk2mrIlf9ZhOlYzwjYzsIFO7esk3WH7lfrWJiQtiKd8CNO2q_BNj5zigg5mg8KWkHvZHjNYKkWtK3hGgsdCV2BIxdjDJFw-Q7xb0YDCXL4NtUX1E5utQ6CpMmVHykH3lFK1iuxaeszcVSW3Qpzenrium35wIzIYDfpA0hffV0_tIvXGF2gypfy-AT0u7ZWUuiMKZGL0wjg_h7mee_nNFm5FfLBImOPihR_NhRf_WecIJsI7uemNmeZUtAv_u4wld9BCg6WI1L-ATOQei3kdpT6IoSs3b1mXKkdcbd5no1PCg6vfUeyVQqrE-v14q3Gz5tDA8r67ZnZFfNQG5GE2RgWcaXwm9Hra5YdeUxcNwTfP0nZZEs6h_wsonBpu_OetrMZuXnsNaf3SPZRuCxyr4AMBv9RSom653dplDvVk9t3tsoKUXVDdV_OxcvhEoBKWJzTrd7-AdXiC9z1N7ptt60Se5_973BYER8sa_RWQV5ccG-qMSYr9zK4Rd8kP5MzmNYxxOjmd-GGrxgFH_MhYDlzEJ_jgqJUXnwCJOg5zt2HYtTtFcNDMS4dBCM0dziIkcu2_tXXdExXo7Dw4Xp-PvMf2_WKPxdEAxsIZgYS-VRhhO49hEYdFYXagZ2iOvn8Tz4We2s6U16kSlq62cfIfq6azdgbhurM4YkRxR8lSHCSHou9hn1fplmBwQ_dclLK4m_G5PtolZMyn3ecdZ4lyz4jqg=w700-h590-no?authuser=0)

6.  Added the route for the new page in `src/constants/routes.js`.

![image 3](https://lh3.googleusercontent.com/7DBty_zjGRFS3UngelX062uxxxetfC5m3Bg8P2j5Mq_H0Kq7ttbLk01yOalYnvqR6vC8OPYVHn0yQ6P5y5LMbm67CriZvrUWaJSyiwMY6S5DH8GRLiOBCqgU-FelxcZlaJStuqt8bXdiWW2Uv1GLUaXA3lIlRtYz_9kI5d-gG5Jzyvck4KUWN9h4tVDNikmdPRVo6asD4DUJ-_xL0oIxdXDWtrJ5Yu7EKl0fKyd6kzQJVCtFWXNogTsQpN1hVJu9ra2dTkjfmnJCftTaKEypWCAxrDTzJUz5ISxTIrFiM6uOnouKNZTdmzfo3TL2k8iUfetkb9Qo8rgVH992okFvwZP7jPykgP1Tc70poxXPmYmFWuEaj0vxPa2SqIlzyrGyj5-tnfI9tQZV3z8hOcVlqAjOjAetEYx_uxKT_ub9Md1fwgwQz3IM9_gkUJam7PN97OnvCIiGYu2JX2Z-A_3XaWweQYyUMpLFzSeVRaP1Uc_y9GxuvE23xipOIkjU0BakTq0KwlfdvIUJ_OiBipAcb6GZLsGI2tX00aAJvMh8Tb0e_-uBYpa49GtSYgrOHrW7wH8NhPKJnF228VPCErtEF1jsCCZq7iYQXvdm66wlLzCmR3O-OkJDUN2W_xaUvINbdPO3wGM6XUGD4gxBwphOK3NxoESNUzYENYrQcqKe8DsDApHUIwiKCnWNsMO0gs29OTSF-r1eLCcYCzPlkL981SBluxghn2oVGag5zgM8G46YGnFAVN1E7sXM_ZT3vQ=w706-h709-no?authuser=0)

### How to test
1. Go in the project's main directory.
2. run command `npm start`
3. Visit the page at `http://localhost:PORT/admin/mantainance` 
4. You should see something looking like this 

##Screenshots
![image4](https://lh3.googleusercontent.com/rHlSSaBZ7MMiKPnddbMRu1R0hPF_3yNG9pfXERNQNdGGUaBBHBqIIW40gxAi_Fa9K9-QtCwZGxX_sj0kDGThtvzKxiZnwSig6nbsfkaY7cFyvVHxS00NngF4xbaUqbjjLM1HLb9v5dbNPcYivzZRkEnqi_LVYkiG-2GWXRU3KfYYWaMq0TPDtue-vcYYYyCKUAvwvK7p-TQ9r8YaaXfTvMqq27nDnj8oRKJ-zvV8Zafxfug62RctZ1Hsx0t9iJKCCY3kPJxunEz3fzbo8QRAxfoRymWWSkUfzLJKtQrfCDFvt2jX35gCSSXwS-MmPnbDVqhly5WOTa7DaWXYbXiJ-GDnWXf1M9nZJzPfRdfidqWF2W7fHMyQ9L7rtCrzOqa7wuInFiajlz5jO8CnKaRZhr6cFg-PYB6wMyxffwD4XHe1SrSHNhbUCPtbYol4XgfajFZOD7Kv-623JC4Abi15ak5t7CYNOeXOgMVdqD8MfsLWVWe2lM4nz2cF0z8Omm24y1i1duB0KwDB4E91A1y_Fk1ejK_qdKkC5783IJAJaHYPPWambjRkRnZ0fWOg8oGoAGt3SSY-eskqoa2o3ZLKzLEZmtIIOnP9lpksRl6B7cqPQJgg3SgG4AARpRSZtnBR3I0eG95C1y7--m3lbSNWF5nZoH0LfXQioOWgd3mzgZJsod42ybsyQHiR_IFNLb6lvR0WcCELpRNJ4EWJIFKRn4z6CR9z6EmwJyEMT6uNDx5qbEgV-6kmMHD0udD2ag=w1912-h899-no?authuser=0)

![image5](https://lh3.googleusercontent.com/E7tO-a_CuGqBC2SZvI2aqvmxFcuV6R1EKMQi3cWuff8fTXqQ2QDrbuqnxMEN2VnTBz4FSNsglcSH-GKRwy-RqdN33AViN9oed8NS7jjt8yTiw3BavWqPyVIwSE6-72JAwgZ01ctPRaKbj3WT_upcVlh6t1q2X6IJYJoQDmtyWJReAU9WGIn0x1jiN3tg59JU_EfJ77cLerEnofe5444QW4ptM7uAdkXEgVv8IwQGXr7Z6gRnIUUSXVPvev0x1rV_CPdGYr8BH4R7_XHV4yuDb2WmKANivLd1F8qk_vTj9JmSA3e0yL0gk8xmILHHzl3TZvsAiJM4IrVcLdnekjJ13G8eU388ayXeSUaHQqBSIkD03McM_gJwEXsfF6SgkFsGyKcejo9PE3pWnrv0WwJYWpRm-4h3UqGWwK6O9scgurBWggklZ31CbCZlA34HemX4eCB1rGZvqgfpa_XSbHIP6qdxQh9W9z4K6R-BSQMQ-AlSm3_HjdjPu5nRv7UlG8hlv_MUslP5TRqdX6C4hS5VYkIKw749cXm_Fmv55v4R7nqZ0LUkmNEpaNMH1ST7Wx0q0q7xNcpTCDM8ZGKgr841BJmZxYI78utwAVVuOFuD_Y5G6kyPvPJKJw0C-r9VGwPLdItwxBa3cU9UQwJUbqVXT4VVjiwAgJT5tUStzlx-1LWJPARh_hdBdQFioOanUBCr_-ng8tTII1LE0XBwDDlISW9I7cEAAKddxhHE89T7RZdWhd1AePwQr8Yln4d2-w=w1920-h897-no?authuser=0)

#### Related Issue:
Fixes #227 

@shaheemazmalmmd @GMishx

2022-06-21 08:09 UTC, GMishx commented
Please consider uploading images directly to PR description. We do not see them due to permission issue
![image](https://user-images.githubusercontent.com/18077542/174749695-19ba3015-13d7-4e52-ae0e-13da7c3c049c.png)

2022-06-21 08:14 UTC, GMishx requested changes
Please remove the `.idea` folder from commit.

2022-06-21 08:14 UTC, GMishx commented on src/constants/routes.js
> -
Please revert unnecessary changes.

2022-06-21 08:14 UTC, GMishx commented on src/pages/Admin/Mantainance/index.jsx
> +    rmvRepoOldFiles2: false,
Can these values be exported to `src/constants/constants.js`?

2022-06-21 08:14 UTC, GMishx commented on src/pages/Admin/Mantainance/index.jsx
> +              verbose (turns on debugging output).
```suggestion
              Verbose (turns on debugging output).
```

2022-06-21 14:21 UTC, dushimsam commented
I have now resolved all queries.
You can review it.

2022-06-23 07:40 UTC, GMishx approved these changes
Changes looks good. Tested, working as expected.

2022-06-23 07:42 UTC, merged

2022-06-23 11:10 UTC, dushimsam commented
that's awesome 👍
thanks