feat(ui): All jobs only accessible by admin
fossology/FOSSologyUI pull request #245
Opened 2022-07-18 08:08 UTC by soham4abc

## Description

- All recent jobs is now only accessible  by admins ( Related with this back-end PR:  https://github.com/fossology/fossology/pull/2260 This needs to be merged first in order to avoid bugs.)
- MyRecentJobs page also implemented.

### Changes
Introduced a new API endpoint and used conditions for the header.

## How to test

Run compile the back-end after PR: ( https://github.com/fossology/fossology/pull/2260 ) is merged and run the server. Use Admin and non-Admin accounts to test out the jobs pages.

## Video 

[Screencast from 18-07-22 01:23:54 PM IST.webm](https://user-images.githubusercontent.com/63705023/179469079-a1990390-aaf9-4958-a2d5-e34bb14271c6.webm)

Fixes #244

PTAL @GMishx @shaheemazmalmmd @Shruti3004

2022-07-19 14:37 UTC, GMishx approved these changes
Changes looks good.

2022-07-24 15:04 UTC, soham4abc commented
Does this require any more changes? @GMishx

2022-08-01 03:04 UTC, soham4abc commented
@GMishx

2022-08-04 13:06 UTC, soham4abc commented
@Shruti3004

2022-08-11 12:19 UTC, Shruti3004 requested changes

2022-08-11 12:19 UTC, Shruti3004 commented on src/api/jobs.js
> +
Please add one liner about your function as documentation

2022-08-11 12:19 UTC, Shruti3004 commented on src/pages/Jobs/MyRecentJobs/index.jsx
> +        for (let i = 0; i < res.res.length; i++) {
Please add condtions there like: 
`res?.res?.length`

2022-08-11 12:19 UTC, Shruti3004 commented on src/services/jobs.js
One liner here as well

2022-08-11 12:46 UTC, soham4abc commented on src/api/jobs.js
> +
resolved

2022-08-11 12:46 UTC, soham4abc commented on src/pages/Jobs/MyRecentJobs/index.jsx
> +        for (let i = 0; i < res.res.length; i++) {
resolved

2022-08-11 12:47 UTC, soham4abc commented on src/services/jobs.js
resolved

2022-08-22 15:46 UTC, soham4abc commented
@Shruti3004 Does this need any more changes??

2022-08-26 07:53 UTC, merged