MananAgr2003/fix/268
fossology/FOSSologyUI pull request #273
Opened 2022-12-18 14:40 UTC by MananAgr2003

## Description

Fixed Issue #268 and improved the navbar in the mobile UI.
Fixed Overflow issue in mobile UI. 

Relevant ScreenShots : 

before : 

![image](https://user-images.githubusercontent.com/92633110/208304441-e0c87fc8-f13c-48e6-b6fb-5f5ed61c16f8.png)

after :

![image](https://user-images.githubusercontent.com/92633110/208304404-48314c40-d387-4065-8d80-589d756a66c3.png)

2022-12-18 19:36 UTC, dushimsam commented
please squash your commits into one

2022-12-19 04:39 UTC, MananAgr2003 commented
@dushimsam I have squashed the PR kindly review it and merge accordingly.

2022-12-31 05:19 UTC, soham4abc commented
@GMishx  @shaheemazmalmmd @Shruti3004 Can you please have a look into this PR?

2023-01-23 19:19 UTC, Shruti3004 requested changes

2023-01-23 19:19 UTC, Shruti3004 commented on src/components/Footer/index.css
> +    max-width: 102vw;
making its width `102vw` will make the footer overflow horizontally.

2023-01-23 19:20 UTC, Shruti3004 commented
Hey @MananAgr2003 please remove the `yarn.lock` changes from your commit.

2025-07-30 06:04 UTC, shaheemazmalmmd commented
We are in a redesign phase of UX so this PR is not valid now.

2025-07-30 06:04 UTC, closed without merging