feat(search): added the search page
fossology/FOSSologyUI pull request #34
Opened 2021-06-25 03:10 UTC by Shruti3004

## Description

Added the Search page

## How to test

Visit the `/search` page

2021-06-27 04:37 UTC, Shruti3004 commented
@GMishx how we get sub folders in this, we are getting the following data : 
```
filename: "$LogFile"
upload:{
    assignee: null
    description: "fossolgy"
    folderid: 1
    foldername: "Software Repository"
    hash:{
        md5: "954DD2992F91C61C91B9280E7986C16F"
        sha1: "3DF4C0B2804E691A29D7ABD00BD4FEFC3D21F36F"
        sha256: "B80A58791BB71D3DE62B595A5556ABB4EA55CF2734C167473B176B8DC047E6B6"
        size: 23953571
   }    
    id: 3,
    uploaddate: "2021-04-02 16:55:29.860327+05:30"
    uploadname: "fossology-master.zip"
}
uploadTreeId: 16134
```

2021-06-28 08:30 UTC, GMishx commented
> @GMishx how we get sub folders in this, we are getting the following data :

Since current REST API does not allow browsing individual files, I made no sense to provide links to that. So, in the response all that's returned is the upload object (same as `/uploads/3`) and the `uploadTreeId` (which is the unique file ID in DB) and `filename` of the matched file.

2021-06-28 08:32 UTC, GMishx commented
I am getting following error. Looks like auth token is missing from request.
```json
{"code":400,"message":"Authorization header is malformed or empty.","type":"ERROR"}
```

2021-06-28 08:32 UTC, Shruti3004 commented
> > @GMishx how we get sub folders in this, we are getting the following data :
> 
> Since current REST API does not allow browsing individual files, I made no sense to provide links to that. So, in the response all that's returned is the upload object (same as `/uploads/3`) and the `uploadTreeId` (which is the unique file ID in DB) and `filename` of the matched file.

Okay, So please checked the way I am representing the data on search page, shall I need to add or subtract anything from it.

2021-06-28 08:35 UTC, Shruti3004 commented
> I am getting following error. Looks like auth token is missing from request.
> 
> ```json
> {"code":400,"message":"Authorization header is malformed or empty.","type":"ERROR"}
> ```

@GMishx, But its working fine for me

2021-06-28 08:38 UTC, GMishx requested changes

2021-06-28 08:38 UTC, GMishx commented on src/pages/Search/index.js
> +    license: " ",
```suggestion
    license: "",
```

2021-06-28 08:38 UTC, GMishx commented on src/pages/Search/index.js
> +              You may also choose one or more odivtional search filters (not
```suggestion
              You may also choose one or more optional search filters (not
```

2021-06-28 08:40 UTC, GMishx commented
> Okay, So please checked the way I am representing the data on search page, shall I need to add or subtract anything from it.

Current implementation is good enough. If you want, you can locally experiment by generating links from the response in format `http://localhost/repo/?mod=view-license&upload=<uploadid>&item=<uploadTreeId>`.

2021-06-28 08:41 UTC, Shruti3004 commented on src/pages/Search/index.js
> +    license: " ",
@GMishx Fixed

2021-06-28 08:41 UTC, Shruti3004 commented on src/pages/Search/index.js
> +              You may also choose one or more odivtional search filters (not
@GMishx Fixed

2021-06-28 08:42 UTC, Shruti3004 commented
> > Okay, So please checked the way I am representing the data on search page, shall I need to add or subtract anything from it.
> 
> Current implementation is good enough. If you want, you can locally experiment by generating links from the response in format `http://localhost/repo/?mod=view-license&upload=<uploadid>&item=<uploadTreeId>`.

Okay Sure

2021-06-28 08:42 UTC, GMishx commented
Now it is working for me (with the `async`).

Can we have the help messages ("You can use '%' as a wild-card, For example: '%v3.war', or 'mypkg%.tar'.") or you are planning them for later?

2021-06-28 08:45 UTC, Shruti3004 commented
> Now it is working for me (with the `async`).
> 
> Can we have the help messages ("You can use '%' as a wild-card, For example: '%v3.war', or 'mypkg%.tar'.") or you are planning them for later?

Yeah Actually I am thinking to prepare a custom component for it like for all the popups to display all the helper messages and error messages

2021-06-28 08:48 UTC, Shruti3004 commented
> > Now it is working for me (with the `async`).
> > Can we have the help messages ("You can use '%' as a wild-card, For example: '%v3.war', or 'mypkg%.tar'.") or you are planning them for later?
> 
> Yeah Actually I am thinking to prepare a custom component for it like for all the popups to display all the helper messages and error messages.

2021-06-28 08:48 UTC, GMishx commented
You can also use [tooltips](https://www.npmjs.com/package/react-tooltip) for help messages.

Do let me know once this PR is ready for merge.

2021-06-28 08:49 UTC, Shruti3004 commented
> You can also use [tooltips](https://www.npmjs.com/package/react-tooltip) for help messages.
> 
> Do let me know once this PR is ready for merge.

@GMishx Should i update the the tooltips in this pr itself?

2021-06-28 08:51 UTC, GMishx commented
If it is not a blocker then it will be better to do it here for the search page. Or it can also be done in a separate PR for other components. Please create an issue if you want to do in separate PR.

2021-06-28 08:57 UTC, Shruti3004 commented
> If it is not a blocker then it will be better to do it here for the search page. Or it can also be done in a separate PR for other components. Please create an issue if you want to do in separate PR.

I think creating issue and doing it in a next pr will be a nicer option because then I will update the previous login code as well with that widgets.

2021-06-28 08:59 UTC, GMishx commented
Sounds good to me :+1:

2021-06-28 09:01 UTC, Shruti3004 commented
> Sounds good to me

@GMishx created the issue #44

2021-06-28 12:05 UTC, Shruti3004 commented
@GMishx Does any other changes required in this pr?

2021-06-30 05:28 UTC, GMishx approved these changes

2021-06-30 05:28 UTC, merged